# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from enum import Enum

class ChannelInfo:
    r"""
    Provides all available channels and their respective names.
    """
    run_led: builtins.bool
    err_led: builtins.bool
    run_switch: builtins.bool
    config_switch: builtins.bool
    outputs: builtins.dict[builtins.int, builtins.str]
    inputs: builtins.dict[builtins.int, builtins.str]
    analog_inputs: builtins.dict[builtins.int, builtins.str]
    analog_outputs: builtins.dict[builtins.int, builtins.str]
    temp_sensors: builtins.dict[builtins.int, builtins.str]
    counter_inputs: builtins.dict[builtins.int, builtins.str]
    pwm_outputs: builtins.dict[builtins.int, builtins.str]
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class AnalogMode(Enum):
    CURRENT = ...
    VOLTAGE = ...

class CntDirection(Enum):
    UP = ...
    DOWN = ...

class CntMode(Enum):
    COUNTER = ...
    ABENCODER = ...

class CntTrigger(Enum):
    RISINGEDGE = ...
    FALLINGEDGE = ...
    ANYEDGE = ...

class InputTrigger(Enum):
    NONE = ...
    RISINGEDGE = ...
    FALLINGEDGE = ...
    BOTHEDGE = ...

class PwmTimebase(Enum):
    NS800 = ...
    MS1 = ...

class TmpMode(Enum):
    RTDTWOWIRE = ...
    RTDTHREEWIRE = ...
    RTDFOURWIRE = ...

class TmpSensorType(Enum):
    PT100 = ...
    PT1000 = ...

def analog_input_get(channel:builtins.int) -> builtins.int:    r"""
    Get value of an analog input (ADC)
    """

def analog_mode_set(channel:builtins.int, mode:AnalogMode) -> None:    r"""
    Set the mode of an analog input
    """

def analog_output_set(channel:builtins.int, value:builtins.int) -> None:    r"""
    Set the value of an analog output (DAC)
    """

def cnt_enable(channel:builtins.int, state:builtins.bool) -> None:    r"""
    Enable the counter or A/B-encoder functionality of a counter.
    """

def cnt_get(channel:builtins.int) -> builtins.int:    r"""
    Get the current counter value
    """

def cnt_set_preload(channel:builtins.int, preload:builtins.int) -> None:    r"""
    Set a start value which will be applied when the counter input gets enabled.
    """

def cnt_setup(channel:builtins.int, mode:CntMode, trigger:CntTrigger, direction:CntDirection) -> None:    r"""
    Setup the mode of operation of a counter input
    """

def get_channel_info() -> ChannelInfo:    r"""
    Get Python object describing all available channels of the system.
    """

def get_config_switch() -> builtins.bool:    r"""
    Get state of the `CONFIG_SWITCH` if available
    """

def get_run_switch() -> builtins.bool:    r"""
    Get state of the `RUN_SWITCH` if available
    """

def input_get(channel:builtins.int) -> builtins.bool:    r"""
    Get state of a digital input
    """

def input_register_callback(channel:builtins.int, callback:typing.Any) -> None:    r"""
    Register a function which will be called if the input signal changes. The callback must have
    the signature `callback(channel: usize, value: bool)`.
    
    Registering the same callback for the same channel twice does not have any effect. Registering
    multiple callback functions for the same channel is possible.
    """

def input_unregister_callback(channel:builtins.int, callback:typing.Any) -> None:    r"""
    Un-register a callback of an input channel. (counterpart of `input_register_callback`)
    """

def output_set(channel:builtins.int, value:builtins.bool) -> None:    r"""
    Set state of a digital output
    """

def pwm_enable(channel:builtins.int, state:builtins.bool) -> None:    r"""
    Enable a PWM output
    """

def pwm_set_timebase(channel:builtins.int, timebase:PwmTimebase) -> None:    r"""
    Set the time base of a PWM channel. Not all PWM channels support all time bases.
    """

def pwm_setup(channel:builtins.int, period:builtins.int, duty_cycle:builtins.int) -> None:    r"""
    Setup the PWM period and duty cycle of a PWM channel.
    """

def set_err_led(value:builtins.bool) -> None:    r"""
    Set state of the `ERROR_LED` if available
    """

def set_run_led(value:builtins.bool) -> None:    r"""
    Set state of the `RUN_LED` if available
    """

def tmp_input_get(channel:builtins.int) -> builtins.float:    r"""
    Get the value of an temperature sensor.
    """

def tmp_set_mode(channel:builtins.int, mode:TmpMode, sensor_type:TmpSensorType) -> None:    r"""
    Set the mode of a temperature sensors. Not all sensors provide all modes and sensor types.
    """

